# Generated by Django 5.0.13 on 2025-03-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('descricao', models.TextField(max_length=100)),
                ('unidade', models.CharField(choices=[('Unidade', 'Unidade'), ('Pacote', 'Pacote'), ('Caixa', 'Caixa'), ('Metro', 'Metro')], max_length=15)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ncm', models.CharField(blank=True, max_length=8, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
            ],
        ),
    ]
