# Generated by Django 5.0.13 on 2025-03-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
