# Generated by Django 5.0.13 on 2025-03-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_produto_ncm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_obra', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cliente', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='imagem',
            new_name='foto',
        ),
    ]
